name: Build Zed Nightly

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Enable long paths in Git
        run: |
          git config --system core.longpaths true

      - name: Enable long paths in Windows
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: zed-industries/zed
          ref: main
      
      - name: Apply patches
        run: |
          curl https://gist.githubusercontent.com/arnopensource/7a93eb0bdd6fecf0d73b6f97be5798ca/raw/45729d8e72d48e1a2aab0a1f149f1dac3d2f521b/no-npm-user-config-reset.patch > no-npm-user-config-reset.patch
          git apply no-npm-user-config-reset.patch
          curl https://gist.githubusercontent.com/solutec-adupere/4b7e30549fb914c1cea409d00fef5b30/raw/4cefcf1a2c6e7b65b92d0b4557e432d13108a5b1/rust-analyzer-windows.patch > rust-analyzer-windows.patch
          git apply rust-analyzer-windows.patch
          
      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: wasm32-wasip1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: zed-release
          path: target/release/zed.exe
